name: DS-Library
main: kr.dreamstory.library.DSLibrary
version: 1.0.0
api-version: 1.18
depend:
  - DreamStory
commands:
  dsitem:
    permission: dreamstory.permission.op
  등급:
    permission: dreamstory.permission.op
permissions:
  dreamstory.permission.op:
    description: 오피 권한
    default: op